version: '3.6'

services:
    mysql:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            - MYSQL_DATABASE=testing
            - MYSQL_USER=joshua
            - MYSQL_PASSWORD=skywalk
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
        volumes:
            - ./volumes/db-data:/var/lib/mysql

    php-fpm:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - ./:/usr/share/nginx/html

    nginx:
        build: docker/nginx
        restart: on-failure
        volumes:
            - ./:/usr/share/nginx/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - 8080:80
        depends_on:
            - php-fpm

    composer:
        image: composer:1.9.0
        command: install
        depends_on:
            - php-fpm
        volumes:
            - .:/app

    pma:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_HOST=mysql
        ports:
            - 8081:80
        depends_on:
            - mysql